FROM gradle:8.5-jdk17 AS build
WORKDIR /app
COPY . /app
RUN gradle buildFatJar --no-daemon

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/build/libs/*-all.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]