server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /products {
        proxy_pass http://server:8080/products;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /payments {
        proxy_pass http://server:8080/payments;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Content-Type $http_content_type;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
