services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - ebiz-net

  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - ebiz-net

networks:
  ebiz-net:
    driver: bridge
