name: SonarCloud Client

on:
  push:
    branches: [main]
    paths:
      - "5/client/**"
      - ".github/workflows/sonar-client.yml"
  pull_request:
    branches: [main]
    paths:
      - "5/client/**"
      - ".github/workflows/sonar-client.yml"

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: 5/client
